# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.7.2"

gem "pg"
gem "pry-rails"
gem "puma"
gem "rails"

gem "sendgrid-ruby"

group :development, :test do
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
end

group :development do
  gem "listen"
end

gem "tzinfo-data", platforms: %i(mingw mswin x64_mingw jruby)
