# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c651de8051a4e6c88fd32de6c4284300b11e112ce2097487ae548dcd0ef86a8f35a849c9929cc085d02e43b53f01a08250fa8ef288697750410b719bcbdf4c1

test:
  secret_key_base: f05a862037497e746110d9fbaad8d56c2f1fd899dffcb5ac0400ee314503f8e9a93aab4d24719be9279980e0cb4a7a2b5342b4b57ced752987cbdc4df71e181e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
